export const ASSIGN_TASK_REQUEST = "ASSIGN_TASK_REQUEST";
export const ASSIGN_TASK_SUCCESS = "ASSIGN_TASK_SUCCESS";
export const ASSIGN_TASK_FAIL = "ASSIGN_TASK_FAIL";

export const ASSIGNMENTS_LIST_REQUEST = "ASSIGNMENTS_LIST_REQUEST";
export const ASSIGNMENTS_LIST_SUCCESS = "ASSIGNMENTS_LIST_SUCCESS";
export const ASSIGNMENTS_LIST_FAIL = "ASSIGNMENTS_LIST_FAIL";
