export const PERSONNELS_LIST_REQUEST = "PERSONNELS_LIST_REQUEST";
export const PERSONNELS_LIST_SUCCESS = "PERSONNELS_LIST_SUCCESS";
export const PERSONNELS_LIST_FAIL = "PERSONNELS_LIST_FAIL";

export const CREATE_PERSONNEL_REQUEST = "CREATE_PERSONNEL_REQUEST";
export const CREATE_PERSONNEL_SUCCESS = "CREATE_PERSONNEL_SUCCESS";
export const CREATE_PERSONNEL_FAIL = "CREATE_PERSONNEL_FAIL";

export const GET_PERSONNEL_BY_ID_REQUEST = "GET_PERSONNEL_BY_ID_REQUEST";
export const GET_PERSONNEL_BY_ID_SUCCESS = "GET_PERSONNEL_BY_ID_SUCCESS";
export const GET_PERSONNEL_BY_ID_FAIL = "GET_PERSONNEL_BY_ID_FAIL";

export const GET_PERSONNELS_LIST_TOTAL_REQUEST =
  "GET_PERSONNELS_LIST_TOTAL_REQUEST";
export const GET_PERSONNELS_LIST_TOTAL_SUCCESS =
  "GET_PERSONNELS_LIST_TOTAL_SUCCESS";
export const GET_PERSONNELS_LIST_TOTAL_FAIL = "GET_PERSONNELS_LIST_TOTAL_FAIL";
