export const PERSONNELS_LIST_REQUEST = "PERSONNELS_LIST_REQUEST";
export const PERSONNELS_LIST_SUCCESS = "PERSONNELS_LIST_SUCCESS";
export const PERSONNELS_LIST_FAIL = "PERSONNELS_LIST_FAIL";

export const CREATE_PERSONNEL_REQUEST = "CREATE_PERSONNEL_REQUEST";
export const CREATE_PERSONNEL_SUCCESS = "CREATE_PERSONNEL_SUCCESS";
export const CREATE_PERSONNEL_FAIL = "CREATE_PERSONNEL_FAIL";
