export const ZONES_VERTS_LIST_REQUEST = "ZONES_VERTS_LIST_REQUEST";
export const ZONES_VERTS_LIST_SUCCESS = "ZONES_VERTS_LIST_SUCCESS";
export const ZONES_VERTS_LIST_FAIL = "ZONES_VERTS_LIST_FAIL";

export const CREATE_ZONE_VERT_REQUEST = "CREATE_ZONE_VERT_REQUEST";
export const CREATE_ZONE_VERT_SUCCESS = "CREATE_ZONE_VERT_SUCCESS";
export const CREATE_ZONE_VERT_FAIL = "CREATE_ZONE_VERT_FAIL";
